name: eventos_da_rep
description: Eventos da REP app.

publish_to: 'none'

version: 1.5.1+9

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  modal_bottom_sheet: ^2.0.1
  intl: ^0.17.0
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  google_sign_in: ^5.3.3
  package_info_plus: ^1.4.2
  flutter_signin_button: ^2.0.0
  provider: ^6.0.3
  flutter_native_splash: ^2.2.3
  infinite_scroll_pagination: ^3.2.0
  shared_preferences: ^2.0.15
  awesome_snackbar_content: ^0.0.5
  firebase_messaging: ^12.0.1
  http: ^0.13.4
  flutter_gravatar: ^2.0.2
  flutter_launcher_icons: ^0.9.3
  map_launcher: ^2.2.3
  flutter_svg: ^1.1.0
  firebase_crashlytics: ^2.8.2
  internet_connection_checker:
  flutter_chat_ui: ^1.6.2
  flutter_chat_types:
  flutter_stripe:
  money2: ^3.1.3
  flutter_credit_card_brazilian: ^2.0.0
  flutter_password_strength: ^0.1.6
  flutter_app_badger: ^1.4.0
  rxdart: ^0.27.5
  loading_animation_widget:
  sign_in_with_apple: ^4.1.0
  device_calendar:
  flutter_native_timezone: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  
  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon2.png"