// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdnE44OstuS-VNw9-iTW9QxgsCylkFpCQ',
    appId: '1:922896371036:web:72f0116cdebd3d9c7ec599',
    messagingSenderId: '922896371036',
    projectId: 'eventos-da-rep',
    authDomain: 'eventos-da-rep.firebaseapp.com',
    storageBucket: 'eventos-da-rep.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmAC7tGBzuSWnCjf7iA1PwiDS4dJOEX9c',
    appId: '1:922896371036:android:73f022650fd609487ec599',
    messagingSenderId: '922896371036',
    projectId: 'eventos-da-rep',
    storageBucket: 'eventos-da-rep.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbFGzBAYxUk-Nq82rnNFp_fN4AtDY-Fk4',
    appId: '1:922896371036:ios:ad4ed3a7725b045f7ec599',
    messagingSenderId: '922896371036',
    projectId: 'eventos-da-rep',
    storageBucket: 'eventos-da-rep.appspot.com',
    androidClientId: '922896371036-rs91th6ge9prl6bt9o2eh2j7q8bcd7cj.apps.googleusercontent.com',
    iosClientId: '922896371036-rp8ebm5jdqubbbp04uiva3hq02khefl1.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventosDaRep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbFGzBAYxUk-Nq82rnNFp_fN4AtDY-Fk4',
    appId: '1:922896371036:ios:ad4ed3a7725b045f7ec599',
    messagingSenderId: '922896371036',
    projectId: 'eventos-da-rep',
    storageBucket: 'eventos-da-rep.appspot.com',
    androidClientId: '922896371036-rs91th6ge9prl6bt9o2eh2j7q8bcd7cj.apps.googleusercontent.com',
    iosClientId: '922896371036-rp8ebm5jdqubbbp04uiva3hq02khefl1.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventosDaRep',
  );
}
